### ISSUE TITLE
Run Sandman as background service

### ISSUE THREAD

**Issue by ameigen** [ameigen/Sandman#3]
Sandman should run as a background service that will only activate when a upload directory meets or exceeds it's designated upload time.

```toml
#...
[directories]
backups = [
    {directory="DIRECTORY_HERE", prefix="PREFIX_NAME", bucket="BUCKET_NAME", start_time="UNIX_TIMESTAMP", upload_interval="SECONDS_BEFORE_UPLOAD"},
]
#...
```
